In [ ]:
import nibabel as nib
import matplotlib.pyplot as plt
import numpy as np

In [18]:
# Specify the path to your .nii file
nii_file_path = 'data/00039_1_SEG_3_PREP_MNI.nii.gz'

# Load the NIfTI image
img = nib.load(nii_file_path)

# Access the image data as a NumPy array
# .get_fdata() returns the image data as a floating-point NumPy array
# .dataobj provides a memory-mapped object, which is useful for large files
image_data = img.get_fdata()

# You can also access the image header and affine transformation matrix
header = img.header
affine = img.affine

# Print some information (optional)
print(f"Image data shape: {image_data.shape}")
print(f"Image data type: {image_data.dtype}")
print(f"Affine transformation matrix:\n{affine}")

Image data shape: (193, 229, 193)
Image data type: float64
Affine transformation matrix:
[[   1.    0.   -0.  -96.]
 [   0.    1.   -0. -132.]
 [   0.    0.    1.  -78.]
 [   0.    0.    0.    1.]]


In [19]:
test = img.get_fdata()[:,:,69]  # Show Random slice
plt.imshow(test)
plt.show()

NameError: name 'plt' is not defined